### ISSUE TITLE
SearchFragment setup with timeline

### ISSUE THREAD

**Issue by yaliza** [Kalyanova/DailyVisualizer#10]

**Comment by Kalyanova** [comment]
To display image with circular corners we can pass Context in `TimeLineDayRecyclerAdapter `constructor and add code like this in `ViewHolder.bind()` method:

```
if(day.getImage() != null){
        Bitmap bitmap = BitmapFactory.decodeByteArray(day.getImage(), 0, day.getImage().length);

        Resources res = context.getResources();
        RoundedBitmapDrawable dr = RoundedBitmapDrawableFactory.create(res, bitmap);
        dr.mutate();
        dr.setCornerRadius(Math.max(dr.getMinimumWidth(), dr.getMinimumHeight()));
        dr.setAntiAlias(true);

        ivPicture.setImageDrawable(dr);
      } else {...}
```

**Comment by Kalyanova** [comment]
But I don't know how to correctly set radius in `dr.setCornerRadius`.  With code from previous comment it looks like this:
![screenshot_20180921-035948_dailyvisualizer](https://user-images.githubusercontent.com/9308897/45854382-7b197000-bd53-11e8-9de8-0fdb0338a800.jpg)
And I've tried a lot of options but unsuccessfully. :sad I suggest to ask mentors tomorrow on Hackathon about it.

**Comment by yaliza** [comment]
> But I don't know how to correctly set radius in `dr.setCornerRadius`. With code from previous comment it looks like this:
> ![screenshot_20180921-035948_dailyvisualizer](https://user-images.githubusercontent.com/9308897/45854382-7b197000-bd53-11e8-9de8-0fdb0338a800.jpg)
> And I've tried a lot of options but unsuccessfully. :sad I suggest to ask mentors tomorrow on Hackathon about it.

I've tried it too :( I think, we can do it later.

**Comment by yaliza** [comment]
I have made a task for it.
